FROM openjdk:11-jdk-slim as build

WORKDIR /app

COPY mvnw .
COPY .mvn .mvn

COPY pom.xml .

RUN ./mvnw dependency:go-offline -B

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y inotify-tools dos2unix

CMD ["sh", "run.sh"]