FROM openjdk:11-jdk-slim

WORKDIR /app

COPY mvnw .
COPY .mvn .mvn

COPY pom.xml .

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y inotify-tools dos2unix

RUN dos2unix mvnw 
RUN ./mvnw dependency:go-offline -B

CMD ["sh", "run.sh"]